version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: make startup
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres